### ISSUE TITLE
DOI reservation, registration, and update for workspaceitem

### ISSUE THREAD

**Issue by marsaoua** [the-library-code/identifiers-enduring-submission#3]
If a User starts a submission process until he/she gets a DOI identifier, and don't finish the submission by saving it, a DOI can be registered, reserved, or update online for this workspaceitem by using the doi-organiser command line.

**Comment by pnbecker** [comment]
That is a difference between DSpace 5 and 6. The method `IdentifierService.reserve(...)` of DSpace 5 (https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace-api/src/main/java/org/dspace/identifier/IdentifierServiceImpl.java#L64-L74) called identifierProvider.mint(...) only. The same method in DSpace 6 (https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/identifier/IdentifierServiceImpl.java#L68-L79) calls mint and reserve.

If we look on the interfaces of the `IdentifierService` and the `IdentifierServiceProvider` we see many identical classes like `reserve`, `register`, `delete`. But the `mint` method is included in the IdentifierServiceProvider only and not in the IdentifierService. We should add such a method to the `IdentifierService`. Than `IdentifierService.reserve()` can actually run the `reserve` methods of the providers while mint could trigger the mint methods only. The Submission step should then call mint of course and not reserve.

As part of this change, we should check the JavaDoc of `IdentifierServiceProvider`. It should be mentioned that calling the mint method twice on the same object must return the same identifier.
